### ISSUE TITLE
Many bugs at main.c lines 20 and 25

### ISSUE THREAD

**Issue by guijan** [f0lg0/CHIP-8#3]
At line 20 of main.c, check_rom() is called. Soon after, load_rom() is called at line 25.
This causes several problems:

check_rom() fopen()s a file and doesn't close it before returning, causing the open FILE to leak. Additionally, it unnecessarily makes any further attempt at opening the file implementation-defined behavior, although I don't know of a C implementation where opening the same file multiple times doesn't just work.

The load_rom() call also fopen()s the same file, without any checking of return values. A non-existing file is not the only cause for an error return of fopen(). 

Even if the above issues are fixed, there is an inherent [TOCTTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) error in doing this. There is no guarantee that the file will still exist by the time load_rom() is called.

The fix is to get rid of the check_rom() function and check the return value of fopen() in load_rom().

**Comment by f0lg0** [comment]
Great finding!
Funny how I was reading about TOCTTOU a couple of days before coding it out but still managed to let it slip through! I can't work at the moment but I will soon, I think I am going to get rid of the check function and handle errors in load_rom().
Thanks again for your efforts!

**Comment by f0lg0** [comment]
[Pacthed](https://github.com/f0lg0/CHIP-8/commit/93e6f84598dc93b1b5630f1357dacffad0c1e00d)
